project:
  type: website

website:
  title: "Data visualization and transformation"
  navbar:
    tools:
        - icon: github
          href: https://github.com/data-science-with-r
    left:
      - href: index.qmd
        text: Home

format: html

mainfont: Atkinson Hyperlegible
theme:
  light: [flatly, style/dsr.scss]
  dark: [darkly, style/dsr-dark.scss]
toc: true
code-link: true
highlight-style: github

execute:
  freeze: auto

editor: visual